apiVersion : apps/v1
kind: Deployment
metadata:
  name: pwitherspoondockermixpanel 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pwitherspoondockermixpanel
  template:
    metadata:
      labels:
        app: pwitherspoondockermixpanel 
    spec:
      containers:
        - name: pwitherspoondockermixpanel 
          image: hrareg.azurecr.io/pwitherspoondockermixpanel
          ports:
          - containerPort: 80